"""Program that calculates the molecular weight of PKC Beta-1 in kilodaltons"""

# Amino acid protein sequence for PKC Beta-1
AMINO_ACIDS = 'MADPAAGPPPSEGEESTVRFARKGALRQKNVHEVKNHKFTARFFKQPTFCSHCTDFIWGFGKQGFQCQVC\
CFVVHKRCHEFVTFSCPGADKGPASDDPRSKHKFKIHTYSSPTFCDHCGSLLYGLIHQGMKCDTCMMNVH\
KRCVMNVPSLCGTDHTERRGRIYIQAHIDREVLIVVVRDAKNLVPMDPNGLSDPYVKLKLIPDPKSESKQ\
KTKTIKCSLNPEWNETFRFQLKESDKDRRLSVEIWDWDLTSRNDFMGSLSFGISELQKAGVDGWFKLLSQ\
EEGEYFNVPVPPEGSEGNEELRQKFERAKIGQGTKAPEEKTANTISKFDNNGNRDRMKLTDFNFLMVLGK\
GSFGKVMLSERKGTDELYAVKILKKDVVIQDDDVECTMVEKRVLALPGKPPFLTQLHSCFQTMDRLYFVM\
EYVNGGDLMYHIQQVGRFKEPHAVFYAAEIAIGLFFLQSKGIIYRDLKLDNVMLDSEGHIKIADFGMCKE\
NIWDGVTTKTFCGTPDYIAPEIIAYQPYGKSVDWWAFGVLLYEMLAGQAPFEGEDEDELFQSIMEHNVAY\
PKSMSKEAVAICKGLMTKHPGKRLGCGPEGERDIKEHAFFRYIDWEKLERKEIQPPYKPKARDKRDTSNF\
DKEFTRQPVELTPTDKLFIMNLDQNEFAGFSYTNPEFVINV'

# Calculate the molecular weight of PKC Beta-1 in kilodaltons
DALTONS = 110
WEIGHT_PKC = (len(AMINO_ACIDS) * DALTONS)
KILO_DALTONS = (WEIGHT_PKC / 1000)

# Print the molecular weight of PKC Beta-1 in kilodaltons
print('The length of "Protein Kinase C beta type" is:', len(AMINO_ACIDS))
print('The average molecular weight of this protein sequence in kilodaltons is:', KILO_DALTONS)
